export const mcVars = {
  background: '--mc-background',
  card: '--mc-card',
  cardHover: '--mc-card-hover',
  semanticBgWarning: '--mc-semantic-bg-warning',
  semanticTextWarning: '--mc-semantic-text-warning',
  semanticBgError: '--mc-semantic-bg-error',
  semanticTextError: '--mc-semantic-text-error',
  semanticBgInfo: '--mc-semantic-bg-info',
  semanticTextInfo: '--mc-semantic-text-info',
  semanticBgSuccess: '--mc-semantic-bg-success',
  semanticTextSuccess: '--mc-semantic-text-success',
  textPrimary: '--mc-text-primary',
  textSecondary: '--mc-text-secondary',
  primary: '--mc-primary',
  primaryBackground: '--mc-primary-background',
  brand: '--mc-brand',
  brandBackground: '--mc-brand-background',
} as const;
